version: "3.4"

services:
  dev:
    build:
      context: .
    volumes:
      - .:/app

  test:
    extends:
      service: dev
    command:
      - ./bin/test

  coverage:
    extends:
      service: dev
    command:
      - ./bin/coverage

  build:
    extends:
      service: dev
    command:
      - ./bin/build
