version: "3.4"

services:
  dev:
    build:
      context: .
    volumes:
      - .:/app
      - bundle:/bundle

  test:
    extends: dev
    command:
      - ./bin/test

  coverage:
    extends: dev
    command:
      - ./bin/coverage

  build:
    extends: dev
    command:
      - ./bin/build
volumes:
  bundle: